import React from 'react';
import FoodsCards from '../Components/FoodsCards';
import AddToCut from '../Components/AddToCut';
import InputField from '../Components/InputField';
const getFoods = async (search) => {
    const res = await fetch(`https://taxi-kitchen-api.vercel.app/api/v1/foods/random?search=${search}`,
        {next:{revalidate:10}}
    );
    const data = await res.json();
    // console.log(data);
    return data.foods
}
//! metaData.
export const metadata = {
  title: "FoodPage",
  description: "Generated by create next app",
};

const FoodsPage = async ({searchParams}) => {
    //? searchParam using get search value;
     const {search=""} = await searchParams;
    //  console.log(search);
    const foods = await getFoods(search);
    // console.log(foods);
    return (
        <div className='max-w-7xl mx-auto'>
            {/* title */}
            <h2 className='text-2xl font-bold text-center my-5'>All {(foods.length)} Foods Found</h2>
            <div>
                {/* Search Input Field here */}
                <InputField></InputField>
            </div>
            {/* Card showing */}
            <div className='flex gap-5'>
                {/* All Card Left side */}
                <div className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {
                        foods.map(food => <FoodsCards key={food.id} food={food}></FoodsCards>)
                    }
                </div>
                {/* right side */}
                <div className='w-[350] border-2 rounded-2xl p-4'>
                    <h1 className='text-2xl font-bold text-center'>Add To Cart Store</h1>
                    {/* Add to all info */}
                    <AddToCut></AddToCut>
                </div>
            </div>

        </div>
    );
};

export default FoodsPage;