import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import ContextProvider from "@/ContextApi/ContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins(
  {
    weight:['400','900']
  }
)

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title:{
    default:"Food_NextJS",
    template:"%s | Food_NextJS"
  } ,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* headder code here */}
        <Header></Header>
        {/* Context provider */}
        <ContextProvider>
          <main>
            {children}
          </main>
        </ContextProvider>
      </body>
    </html>
  );
}
