import React from 'react';
import ReviewsPage from './ReviewsPage';
//? Meta data.
export const metadata = {
  title:{
    absolute:"user saticsfy"
  },
// title:"user saticsfy",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            {/* server page */}
            <ReviewsPage></ReviewsPage>
        </div>
    );
};

export default page;